### ISSUE TITLE
Értékelés

### ISSUE THREAD

**Issue by aron123** [NGergelyTibor/InfRendszerBProf2023#2]
# Összesítés

Feladat | Eredmény | Megjegyzés
------- | :------: | ----------
[4. hét](https://aron123.github.io/infrend-2023/bprof.html#ht-1) | :heavy_check_mark: | -
[5-6. hét](https://aron123.github.io/infrend-2023/bprof.html#ht-2) | :heavy_check_mark: | -
[7. hét](https://aron123.github.io/infrend-2023/bprof.html#ht-3) | :heavy_check_mark: | -
[8. hét](https://aron123.github.io/infrend-2023/bprof.html#ht-3) | :heavy_check_mark: | -
[9. hét](https://aron123.github.io/infrend-2023/bprof.html#ht-3) | :heavy_check_mark: | -
[11-12. hét](https://aron123.github.io/infrend-2023/bprof.html#ht-5) | :heavy_check_mark: | -

<details>
<summary>Jelmagyarázat</summary>

:heavy_check_mark: elfogadva, minden követelményt teljesít

:warning: elfogadva, de nem teljesít minden követelményt

:x: nem elfogadható, javítani szükséges
</details>

- Ha elkészültél egy feladattal, kérlek, hogy kommentben jelezd!
- Ha segítségre van szükséged, kérlek, hogy kommentben vagy e-mailben jelezd!

**Comment by aron123** [comment]
A 7-8. heti feladat alapvetően rendben van, de jobb jegyért javítható még:

- a két kereső felület között menürendszerrel lehessen navigálni
- a user keresőnek a repository keresőhöz hasonlóan több találatot kellene megjelenítenie, nem pontos felhasználónév egyezésre keresnie
- a hasonló, lekérdezéseket tartalmazó függvényeket ki kellene szervezni service-kbe (lehet akár külön User és RepoService vagy akár csak egy GitHubService):
    https://github.com/NGergelyTibor/InfRendszerBProf2023/blob/b9d910e4e6e1234c6ac55cce1da299eb729b1452/HatodikHet/GithubSearch/src/app/user-search/user-search.component.ts#L19


Ha a 9. heti feladat (adatlapok) elkészült, akkor az ehhez tartozó API hívásokat is dokumentálni kellene az [HatodikHetGithubAPI.md](https://github.com/NGergelyTibor/InfRendszerBProf2023/blob/main/HatodikHet/HatodikHetGithubAPI.md)-ben.

**Comment by NGergelyTibor** [comment]
Megcsináltam az összes követelmény, és megcsináltam a 9. heti feladatot is.

**Comment by aron123** [comment]
Szuper, rendben vannak a megoldások!

**Comment by NGergelyTibor** [comment]
Kész van a 11-12. heti feladat is.
